services:
    auriga.listener.addcustomregexp:
        class: Hschottm\AurigaBundle\EventListener\AddCustomRegexpListener
        tags:
            - { name: contao.hook, hook: addCustomRegexp, method: addCustomRegexp, priority: 0 }
        arguments:
            - "@contao.framework"
        public: true
